### ISSUE TITLE
Reply icon hidden

### ISSUE THREAD

**Issue by carlmylo** [CroissantDuNord/discord-adblock#19]
<img width="392" alt="Screen Shot 2024-01-02 at 10 53 21 AM" src="https://github.com/CroissantDuNord/discord-adblock/assets/56451149/6acf5585-b0cd-40a0-b17b-a3fd38a0cbc7">

Enabling the CSS seems to hide the reply icon, so one will have to hold shift to access it.

**Comment by nixRidge** [comment]
Thank you! Seems there are a couple of now-redundant rules in the CSS, so I will go ahead and comment them out. When you have the chance, please check if it's fixed for you.

**Comment by carlmylo** [comment]
Reply button is back! However, I noticed the text input box's gift icon shows up. No idea if that's on my end.
![image](https://github.com/CroissantDuNord/discord-adblock/assets/56451149/cbae05da-1717-46de-82b5-407065fa6438)

**Comment by nixRidge** [comment]
Oops! Thanks for testing so quickly.

I just realised, this is because I have the send button enabled on my end, so it counts as one of the childs in that block of buttons. Therefore, the gift button is child number 5 for me, but number 4 for people who use the default setting (no reply button).
I completely forgot I was using that non-standard setting 🤦‍♀️
![bilde](https://github.com/CroissantDuNord/discord-adblock/assets/40672277/7313859f-17ba-42b7-adb4-f90a566a4943)

I suppose the only way to get rid of that one is to match its class, but I'm always a bit hesitant to do so since a lot of buttons in Discord often take on the same class. However this one seems safe, just need to update it whenever Discord is updated with new randomised classes.

Could I bug you to test this rule, to make sure it only removes the gift button on your end too?
```
/* Gift button */
#app-mount > div.appAsidePanelWrapper__714a6 > div.notAppAsidePanel__9d124 > div.app_b1f720 > div > div.layers__1c917.layers_a23c37 > div > div > div > div > div.chat__52833 > div.content__1a4fe > div > div.chatContainer__23434 > main > form > div > div.scrollableContainer__33e06.themedBackground__6b1b6 > div > div.buttons_ce5b56 > button.button_afdfd9.lookBlank__7ca0a.colorBrand_b2253e.grow__4c8a4 {
    display: none
}
```

**Comment by carlmylo** [comment]
Adding that to the QuickCSS file seems to have made the gift icon disappear. Everything else seems to be fine.

**Comment by nixRidge** [comment]
Then I'll push that and close this issue, many thanks for your help =)
