### ISSUE TITLE
Doesn't Seem to Work Anymore

### ISSUE THREAD

**Issue by KingJigglypuff** [CroissantDuNord/discord-adblock#28]
Granted, I'm using BetterDiscord when this theme recommends Vencord, but my issue is that since last month or earlier, this stopped working for me.

I'm unsure whether or not this is an issue with the theme itself or with how BetterDiscord handles custom CSS.

**Comment by ac615223s5** [comment]
what is the content of your css file? does it match https://github.com/CroissantDuNord/discord-adblock/blob/main/README.md?

**Comment by KingJigglypuff** [comment]
I simply used the import line from the readme. Would I instead grab the css file, and put it into the BetterDiscord themes folder?

**Comment by ac615223s5** [comment]
importing should work...

**Comment by KingJigglypuff** [comment]
If it should work, then I'd presume it'd be a BetterDiscord issue. I'll bring it up on their Discord and report back.

**Comment by KingJigglypuff** [comment]
Alright, I've got some information from the BetterDiscord server. The issue comes from this theme being outdated. The `data-list-item-id` function is no longer supported by more recent BetterDiscord versions.

**Comment by speedlorenzo12** [comment]
for some fixes you can use this site (not like data-list-item-child i guess). And this should have a true and false nitro variable because it could create chaos if someone uses nitro
https://syndishanx.github.io/Website/Update_Classes.html

**Comment by nixRidge** [comment]
Are you using it as a theme, instead of Custom CSS?

**Comment by KingJigglypuff** [comment]
I mentioned earlier that I used the import line from the readme under Custom CSS. I also mentioned earlier that updates to BetterDiscord removed support for some functions the script uses.

**Comment by nixRidge** [comment]
And right you did, I just saw mention of using the themes function instead and double checked in my sleep deprived state, was kind of glossing over everything that had been going on the past few months while I wasn't using Discord.

Anyway, I'm giving it a shot in a BetterDiscord-enabled client and my latest updates, not using any themes at all just the bone-stock Discord theme on Linux if that even matters, though I doubt it.
It seems to be working fine, even the data-list-item-id matches, so I'm unsure what's broken.. I can't promise anything because I'll be fairly busy the coming week but I'll try to look into it and see what's up.

**Comment by KingJigglypuff** [comment]
Is there anything I could do to help troubleshoot what could be wrong on my end?

**Comment by nixRidge** [comment]
Yeah, when you have time, could you try just pasting the entire contents (or just a small part) of adblock.css directly into your custom CSS? Preferably, if you only copy parts of it, try some of the data-list-item-id rules, because they all work perfectly for me, unfathomably.

It's also relying a lot less on matching the randomised class names now, but are you using PTB or Canary perhaps? Wondering if the code that needs to be targeted is somehow different there but.. not so sure about that. I'm a bit out and about lately so I don't really have an opportunity to sit down and try the PTB/canary versions.

Also, on any kind of Nitro ad, shop button, etc that shows up, feel free to paste the full HTML for its div here.
(Developer tools with CTRL+Shift+i, then use the element picker by pressing CTRL+Shift+c to click on some unwanted element. You can then copy the HTML for its entire element. Right click on the parent div and then "Edit as HTML", paste it here in a code block, or screenshot, whichever works best for you.)

Thanks!

**Comment by KingJigglypuff** [comment]
I'm on the stable branch of Discord. Though interestingly enough, both Discord and the BetterDiscord BDFDB plugins updated recently, and the script started working again. So I'll close this issue for the time being.

**Comment by nixRidge** [comment]
Ok, that's great to hear! If it ever stops working again I'll do my best to help 😃
