### ISSUE TITLE
Remove the new "Apps & Commands" button

### ISSUE THREAD

**Issue by VL4DST3R** [CroissantDuNord/discord-adblock#33]
Today I noticed a new button popped up next to the message field after the gif/sticker/emoji buttons.

It's useless and would love to get rid of it.

![image](https://github.com/user-attachments/assets/cee0dbcf-52a5-4fed-823f-9dabbe558f09)

EDIT: found this filter rule for UBO mentioned on a [reddit thread](https://www.reddit.com/r/discordapp/comments/1exfexd/is_there_a_way_to_turn_off_this_feature_is_take/lj6e31g/) and figured it could be useful:

`discord.com##div[class^="channelAppLauncher"]`

**Comment by nixRidge** [comment]
Heya, and thanks for the issue.

I've already blocked this in the new adblock-extras file, where by request, I've moved anything that isn't strictly ads so people can keep things like profile customisations and still block ads.

Do you think this rule should be moved to the main list?

Cheers!

**Comment by VL4DST3R** [comment]
> Do you think this rule should be moved to the main list?

Hey, thanks for the reply! Honestly? yes, as people mentioned on that reddit thread, this thing is 99% ads and garbage sponsored apps, plus it messes with the layout eating up space for narrow screens more than it is of any real use.

Moreover having it on the extras file would mean people would be also removing the rest of the features present there, something which many (for example myself) may not want.

**Comment by nixRidge** [comment]
Agreed, I'll move it. Thank you.

**Comment by VL4DST3R** [comment]
As time goes on this may actually become a bigger issue, with more and more questionable features being added, and I'm not sure if adding separate lists for them is the most sustainable approach.

Having this as a proper vencord/bd plugin would be the most flexible approach but I guess its not really urgent yet. "Cross that bridge when you get there" and all that.

**Comment by nixRidge** [comment]
I'm with you on that, I have actually been looking into making this a Vencord plugin that lets people pick what they want to block. Problem is I'm drawing complete blanks on how that'd work, for now. Need to sit down and properly learn how to work with TypeScript when I have free time.

The split lists are just a stopgap solution for the time being. However another problem with such a plugin would be how often the plugin can be updated on Vencord, since the plugins are all built with Vencord itself. Though, if the plugin could load external css files then no biggie.

**Comment by polyjitter** [comment]
One small caveat is that this is actually pretty useful if you actually have bots with slash commands within your server, as it gives you a list of all the slash commands for any bot in the server:

![Image](https://github.com/user-attachments/assets/c7d5d938-2710-4331-92ed-882d8d6e4785)

![Image](https://github.com/user-attachments/assets/9d359205-d432-4456-b789-2d58e4962729)

(Ignore some of the recents, I was testing some stuff out.)

Very helpful if you don't have every slash command memorized (especially since most slash-based bots no longer have help commands). Perhaps an option should exist to show only the "Recent and "Apps in this Server" sections, but hide everything else?

**Comment by nixRidge** [comment]
I agree, at that point this is more of a useful feature than strictly ads and marketing. The problem with CSS lists like these is you don't get much options. You either import the entire list, or you cherry-pick which rules you want from the two lists and have to keep it manually updated.

My intention with the CSS extras list was for people to do just that, open the list and pick the rules they specficially want to block, but it seems like a lot of people just subscribe to the entire list out of convenience, regardless of it blocking what they like or not.

I'll see if I can come up with a middle-ground solution to this, but I'll most likely just move the "app picker" back to extras because from your example I deem it to be on the useful side.
I like your idea about blocking elements within it and keeping recents and server apps. Is this via the app picker icon?

**Comment by polyjitter** [comment]
Yeah, it's within the app picker icon :) Seems to be the same CSS class since the script still works but they updated it to look like a game controller for some reason?

**Comment by nixRidge** [comment]
Appreciate it polyjitter. As with most things I "may or may not get around to it", but it's definitely something I want to look into, lol :)
