### ISSUE TITLE
New Activity tracker/remove friends.

### ISSUE THREAD

**Issue by radianthero** [CroissantDuNord/discord-adblock#34]
The new activity tracker can be disabled/ but it'll still show in the top right, any way to get rid of it?

Also, with all your patches (thank you so much for them btw) it leaves the friends list at the top showing Friends

![image](https://github.com/user-attachments/assets/2e17d8e5-cfa1-4c55-9252-302149782d63)

But the tab itself no longer needs to be shown, is there a way to remove it? Thanks!

**Comment by nixRidge** [comment]
Hey there, thanks for the issue, and sorry it took so long to get back.

I'll add a rule for the activity tracker to the extra list (didn't even know of it until now!)
As for the friends button, I decided to leave that alone, because people may still need to actually access the friends view, in order to open DMs or add new friends, manage blocked, etc.

Nevertheless, you can always remove it yourself with this rule:
```css
div[class^=friendsButtonContainer_] {
    display: none;
}
```

If I'm misinterpreting and missed the point of removing the friends button, you can always feel free to re-open this issue. Thank you again!
